exclude: >
  (?x)^(
    .*\.svg|
    .*\.md|
    .*\.ui|
    .*\.ts|
    .*\.qm
  )$
minimum_pre_commit_version: 1.13.0
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
        args: [--max-line-length=99]
